ecosite/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static
from .api.signup import SignupApiView
from .api.signin import SigninService

app_name = 'ecosite'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('statistics/', views.statistics, name='statistics'),
    path('api/quit/', views.quit, name='quit'),
    path('api/signup/', SignupApiView.as_view()),
    path('api/signin/', SigninService.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hedgehog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecosite.urls'))
]

ecosite/models.py
import uuid
from django.db import models


class AccountModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False)
    email = models.CharField(max_length=40)
    password = models.CharField(max_length=40)

ecosite/views.py
from django.shortcuts import render
from .models import AccountModel
from loguru import logger

from .utils.get_user_data import get_user_data


def index(request):
    return render(request, 'ecosite/index.html', get_user_data(request))


def about(request):
    return render(request, 'ecosite/about.html', get_user_data(request))


def registration(request):
    return render(request, 'ecosite/registration.html')


def login(request):
    return render(request, 'ecosite/login.html')


def statistics(request):
    return render(request, 'ecosite/statistics.html', get_user_data(request))

def profile(request):
    return render(request, 'ecosite/profile.html', get_user_data(request))


def quit(request):
    if "account_id" in request.session:
        email = AccountModel.objects.filter(id=request.session["account_id"])[0].email
        logger.info(f"User {email} terminated session on their account")

        del request.session["account_id"]

    return render(request, 'ecosite/login.html')

ecosite/templates/ecosite/about.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog - О нас{% endblock %}

{% block custom_styles %}
<link href="../static/css/carousel.css" rel="stylesheet">
<link href="../static/css/headers.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="{% url 'ecosite:index' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <img src="../../static/FullLogo.png" width="50%" height="50%" role="img"/>
                </a>
            </div>
            <ul class="nav col-12 col-md-auto mb-2 mb-md-0">
                <li><a href="{% url 'ecosite:index' %}" class="nav-link px-2">Главная</a></li>
                <li><a href="{% url 'ecosite:statistics' %}" class="nav-link px-2">Статистика</a></li>
                <li><a href="{% url 'ecosite:about' %}" class="nav-link px-2 link-secondary">О нас</a></li>
            </ul>
            <div class="col-md-3 text-end">
              {% if not authorized %}
                <a href="{% url 'ecosite:login' %}">
                    <button type="button" class="btn btn-primary">Войти</button>
                </a>
              {% else %}
                <ul class="nav col-12 mb-2 mb-md-0 col-md-auto justify-content-end">
                    <li class="text-center d-flex align-items-center"><a href="{% url 'ecosite:profile' %}" class="nav-link px-2">{{ email }}</a></li>
                    <li class="text-center d-flex align-items-center"><a class="nav-link px-2"><button type="submit" class="btn btn-primary" onclick="quit()">Выйти</button></a></li>
                </ul>
              {% endif %}
            </div>
        </header>
    </div>
</main>
<body>
  <main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/FirstSlide.jpg"></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Сделаем Алматы лучше!</h1>
            <!-- <p>Some representative placeholder content for the first slide of the carousel.</p> -->
            <!-- <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p> -->
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/SecondSlide.jpg"></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Только мы!</h1>
            <!-- <p>Some representative placeholder content for the second slide of the carousel.</p> -->
            <!-- <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p> -->
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/ThirdSlide.jpg"></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Вместе!</h1>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Забота о природе и удобство навигации в одном месте.</h2>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/FirstHeader.svg"></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">Принципы экологической переработки</h2>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/SecondHeader.svg"></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Уникальная возможность помочь городу</h2>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><image width="100%" height="100%" xlink:href="../../static/ThirdHeader.svg"></image></svg>
      </div>
    </div>

    <hr class="featurette-divider">
    </div>
{% endblock %}

{% block custom_scripts %}
<script type="text/javascript" src="../static/js/auth/quit.js"></script>
{% endblock %}

ecosite/templates/ecosite/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <meta name="description" content="">
	  <meta name="generator" content="Hugo 0.111.3">
	  <link rel="shortcut icon" href="../../static/icon.png"/>
	  <title>{% block title %}{% endblock %}</title>
		<link href="../../static/css/bootstrap.min.css" rel="stylesheet">
		<link href="
		https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css
		" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>
    {% block custom_styles %}
    {% endblock %}
  </head>
  <body class="text-center">
  	{% block content %}
  	{% endblock %}
  	{% block custom_scripts %}
  	{% endblock %}
  	<script src="../../static/js/bootstrap.bundle.min.js"></script>
		<script type="text/javascript" src="../../static/js/libs/sweetalert2.min.js"></script>
		<script type="text/javascript" src="../../static/js/libs/jquery.min.js"></script>
	</body>
</html>

ecosite/templates/ecosite/index.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog{% endblock %}
{% block custom_styles %}
<link href="../static/css/headers.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="{% url 'ecosite:index' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <img src="../../static/FullLogo.png" width="50%" height="50%" role="img"/>
                </a>
            </div>
            <ul class="nav col-12 col-md-auto mb-2 mb-md-0">
                <li><a href="{% url 'ecosite:index' %}" class="nav-link px-2 link-secondary">Главная</a></li>
                <li><a href="{% url 'ecosite:statistics' %}" class="nav-link px-2">Статистика</a></li>
                <li><a href="{% url 'ecosite:about' %}" class="nav-link px-2">О нас</a></li>
            </ul>
            <div class="col-md-3 text-end">
              {% if not authorized %}
                <a href="{% url 'ecosite:login' %}">
                    <button type="button" class="btn btn-primary">Войти</button>
                </a>
              {% else %}
                <ul class="nav col-12 mb-2 mb-md-0 col-md-auto justify-content-end">
                    <li class="text-center d-flex align-items-center"><a href="{% url 'ecosite:profile' %}" class="nav-link px-2">{{ email }}</a></li>
                    <li class="text-center d-flex align-items-center"><a class="nav-link px-2"><button type="submit" class="btn btn-primary" onclick="quit()">Выйти</button></a></li>
                </ul>
              {% endif %}
            </div>
        </header>
    </div>
</main>
{% endblock %}

{% block custom_scripts %}
<script type="text/javascript" src="../static/js/auth/quit.js"></script>
{% endblock %}

ecosite/templates/ecosite/login.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog - Вход{% endblock %}

{% block custom_styles %}
<link href="../../static/css/sign-in.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../../static/FullLogo.png" alt="" width="100%" height="100%">
    <h1 class="h3 mb-3 fw-normal">Вход</h1>
    <p class="mb-3">Еще не зарегистрировались? Тогда вам <a href="{% url 'ecosite:registration' %}">сюда</a></p>
  </form>
  <form>
    <div class="form-floating">
      <input type="email" class="form-control email-input" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Адрес электронной почты</label>
    </div>
  </form>
  <form>
    <div class="form-floating">
      <input type="password" class="form-control password-input" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Пароль</label>
    </div>
  </form>
    <button class="w-100 btn btn-lg btn-primary" type="submit" onclick="signin()">Войти</button>
  </form>
</main>
{% endblock %}

{% block custom_scripts %}
<script type="text/javascript" src="../../static/js/auth/signin.js"></script>
{% endblock %}

ecosite/templates/ecosite/profile.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog - Профиль{% endblock %}

{% block custom_styles %}
<link href="../static/css/headers.css" rel="stylesheet">
<link href="../static/css/style.css" rel="stylesheet">
{% endblock %}

{% block content %}

<main>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="{% url 'ecosite:index' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <img src="../../static/FullLogo.png" width="50%" height="50%" role="img"/>
                </a>
            </div>
            <ul class="nav col-12 col-md-auto mb-2 mb-md-0">
                <li><a href="{% url 'ecosite:index' %}" class="nav-link px-2">Главная</a></li>
                <li><a href="{% url 'ecosite:statistics' %}" class="nav-link px-2">Статистика</a></li>
                <li><a href="{% url 'ecosite:about' %}" class="nav-link px-2 link-secondary">О нас</a></li>
            </ul>
            <div class="col-md-3 text-end">
              {% if not authorized %}
                <a href="{% url 'ecosite:login' %}">
                    <button type="button" class="btn btn-primary">Войти</button>
                </a>
              {% else %}
                <ul class="nav col-12 mb-2 mb-md-0 col-md-auto justify-content-end">
                    <li class="text-center d-flex align-items-center"><a href="{% url 'ecosite:profile' %}" class="nav-link px-2">{{ email }}</a></li>
                    <li class="text-center d-flex align-items-center"><a class="nav-link px-2"><button type="submit" class="btn btn-primary" onclick="quit()">Выйти</button></a></li>
                </ul>
              {% endif %}
            </div>
        </header>
    </div>
</main>
<header class="ScriptHeader">
    <div class="container">
    	<div class="rt-12">
        	<div class="heading">
            	<h1>Профиль</h1>
            </div>
        </div>
    </div>
</header>

<section>
    <div class="rt-container">
          <div class="col-rt-12">
              <div class="Scriptcontent">
              
<!-- Student Profile -->
<div class="student-profile py-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent text-center">
            <h3>{{ email }}</h3>
          </div>
          <div class="card-body">
            <p class="mb-0"><strong class="pr-1">Город заданий:</strong>Алматы</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent border-0">
            <h3 class="mb-0"><i class="far fa-clone pr-1"></i> <br>Бутылок собрано за сегодня: </h3>
          </div>
          <div class="card-body pt-0">
            <table class="table table-bordered">
            </table>
          </div>
        </div>
      </div>
      <h3>
        Button for bottles
      </h3>
    </div>
  </div>
</div>
    		</div>
		</div>
    </div>
</section>
{% endblock %}

ecosite/templates/ecosite/registration.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog - Регистрация{% endblock %}

{% block custom_styles %}
<link href="../../static/css/sign-in.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../../static/FullLogo.png" alt="" width="100%" height="100%">
    <h1 class="h3 mb-3 fw-normal">Регистрация</h1>
  </form>
  <form>
    <div class="form-floating">
      <input type="email" class="form-control email-input" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Адрес электронной почты</label>
    </div>
  </form>
  <form>
    <div class="form-floating">
      <input type="password" class="form-control password-input" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Пароль</label>
    </div>
  </form>
  <form>
    <div class="form-floating">
      <input type="password" class="form-control confirmed-password-input" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Подтвердите пароль</label>
    </div>
  </form>
  <button class="w-100 btn btn-lg btn-primary" type="submit" onclick="signup()">Зарегистрироваться</button>
</main>
{% endblock %}

{% block custom_scripts %}
<script type="text/javascript" src="../../static/js/auth/signup.js"></script>
{% endblock %}

ecosite/templates/ecosite/statistics.html
{% extends 'ecosite/base.html' %}

{% block title %}Hedgehog - Статистика{% endblock %}

{% block custom_styles %}
<link href="../static/css/headers.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main>
  <div class="container">
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <div class="col-md-3 mb-2 mb-md-0">
              <a href="{% url 'ecosite:index' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
                  <img src="../../static/FullLogo.png" width="50%" height="50%" role="img"/>
              </a>
          </div>
          <ul class="nav col-12 col-md-auto mb-2 mb-md-0">
              <li><a href="{% url 'ecosite:index' %}" class="nav-link px-2">Главная</a></li>
              <li><a href="{% url 'ecosite:statistics' %}" class="nav-link px-2">Статистика</a></li>
              <li><a href="{% url 'ecosite:about' %}" class="nav-link px-2 link-secondary">О нас</a></li>
          </ul>
          <div class="col-md-3 text-end">
            {% if not authorized %}
              <a href="{% url 'ecosite:login' %}">
                  <button type="button" class="btn btn-primary">Войти</button>
              </a>
            {% else %}
              <ul class="nav col-12 mb-2 mb-md-0 col-md-auto justify-content-end">
                  <li class="text-center d-flex align-items-center"><a href="{% url 'ecosite:profile' %}" class="nav-link px-2">{{ email }}</a></li>
                  <li class="text-center d-flex align-items-center"><a class="nav-link px-2"><button type="submit" class="btn btn-primary" onclick="quit()">Выйти</button></a></li>
              </ul>
            {% endif %}
          </div>
      </header>
  </div>
</main>

<div>
  <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
      datasets: [{
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    }
  });
</script>

{% endblock %}